# Generated by Django 5.0.7 on 2024-07-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platform',
            new_name='stram',
        ),
    ]
