# Generated by Django 5.0.7 on 2024-07-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_rename_platform_watchlist_stram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist_app.streamplatform'),
        ),
    ]
