# Generated by Django 5.0.7 on 2024-07-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_alter_watchlist_stram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='stram',
            new_name='stream',
        ),
    ]
